---

- name: Add webupd8 repository
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

- name: Auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install Java8
  apt: name=oracle-java8-installer state=latest
